package ny.rina;
/*
 * This source file was generated by the Gradle 'init' task
 */

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application{

    @Override
    public void start(Stage primaryStage) throws Exception{
        Parent root  = FXMLLoader.load(getClass().getResource("/view/media.fxml"));
        primaryStage.setTitle("VAzo media");
        primaryStage.setScene(new Scene(root, 600, 400));
        primaryStage.show();
    }
    public static void main(String[] args) {
        launch(args);
    }
}
