/*
 * This source file was generated by the Gradle 'init' task
 */


import org.junit.jupiter.api.Test;

import ny.rina.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
}
